#!/usr/bin/env bash

if
  [[ -s "/home/gitpod/.rvm/gems/ruby-2.4.6/environment" ]]
then
  source "/home/gitpod/.rvm/gems/ruby-2.4.6/environment"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/gitpod/.rvm/gems/ruby-2.4.6/environment'" >&2
  exit 1
fi
