#!/usr/bin/env bash

if
  [[ -s "/home/gitpod/.rvm/gems/ruby-2.5.5/environment" ]]
then
  source "/home/gitpod/.rvm/gems/ruby-2.5.5/environment"
  exec ruby_executable_hooks "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/gitpod/.rvm/gems/ruby-2.5.5/environment'" >&2
  exit 1
fi
