#!/usr/bin/env bash

if
  [[ -s "/home/gitpod/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/environment" ]]
then
  source "/home/gitpod/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/environment"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/gitpod/.rvm/rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/environment'" >&2
  exit 1
fi
